# Generated by Django 5.2.8 on 2026-02-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_alter_gameobject_object_type'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImportedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_by_users', to='compendium.gameobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'game_object'), name='unique_user_imported_object')],
            },
        ),
    ]
