# Generated by Django 5.2.8 on 2026-02-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednote',
            name='content',
            field=models.CharField(blank=True, default='', max_length=65535),
        ),
    ]
