# Generated by Django 5.2.15 on 2026-06-12 16:34

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_scratchpads(apps, schema_editor):
    """Keep each user's most recently updated scratchpad; drop the rest."""
    SharedNote = apps.get_model('notes', 'SharedNote')
    seen_users = set()
    duplicates = []
    queryset = SharedNote.objects.filter(title='Scratchpad', visibility='private').order_by(
        '-updated_at', '-id'
    )
    for note in queryset.only('id', 'created_by_id').iterator():
        if note.created_by_id in seen_users:
            duplicates.append(note.pk)
        else:
            seen_users.add(note.created_by_id)
    if duplicates:
        SharedNote.objects.filter(pk__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_sharednote_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_scratchpads, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sharednote',
            constraint=models.UniqueConstraint(condition=models.Q(('title', 'Scratchpad'), ('visibility', 'private')), fields=('created_by',), name='unique_private_scratchpad_per_user'),
        ),
    ]
