# Generated by Django 5.1 on 2026-02-08 22:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(choices=[('monster', 'Monster'), ('spell', 'Spell'), ('item', 'Item'), ('character', 'Character'), ('npc', 'NPC'), ('misc', 'Misc')], db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('official', 'Official'), ('imported', 'Imported'), ('custom', 'Custom')], db_index=True, max_length=32)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be in #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('system', models.CharField(db_index=True, max_length=64)),
                ('is_system_tag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameObjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium.gameobject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compendium.tag')),
            ],
        ),
        migrations.AddField(
            model_name='gameobject',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='game_objects', through='compendium.GameObjectTag', to='compendium.tag'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('game_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='compendium.gameobject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'game_object'), name='unique_user_game_object_favorite')],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['system', 'name'], name='compendium__system_92578b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('system', 'name'), name='unique_tag_name_per_system'),
        ),
        migrations.AddConstraint(
            model_name='gameobjecttag',
            constraint=models.UniqueConstraint(fields=('game_object', 'tag'), name='unique_game_object_tag'),
        ),
        migrations.AddIndex(
            model_name='gameobject',
            index=models.Index(fields=['system', 'object_type', 'name'], name='compendium__system_1592ff_idx'),
        ),
        migrations.AddIndex(
            model_name='gameobject',
            index=models.Index(fields=['system', 'external_id'], name='compendium__system_6bc36b_idx'),
        ),
    ]
