# Generated by Django 5.2.8 on 2026-02-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='object_type',
            field=models.CharField(choices=[('monster', 'Monster'), ('spell', 'Spell'), ('item', 'Item'), ('class', 'Class'), ('race', 'Race'), ('feat', 'Feat'), ('background', 'Background'), ('character', 'Character'), ('npc', 'NPC'), ('misc', 'Misc')], db_index=True, max_length=32),
        ),
    ]
