# Generated by Django 5.2.8 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compendium", "0002_alter_gameobject_object_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("monster", "Monster"),
                    ("spell", "Spell"),
                    ("item", "Item"),
                    ("class", "Class"),
                    ("race", "Race"),
                    ("feat", "Feat"),
                    ("background", "Background"),
                    ("condition", "Condition"),
                    ("character", "Character"),
                    ("npc", "NPC"),
                    ("misc", "Misc"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
