# Generated by Django 5.2.15 on 2026-06-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def blank_duplicate_external_ids(apps, schema_editor):
    """Clear external_id on later duplicates so the unique constraint can apply.

    Rows are kept (they may be referenced by games/favorites/imports); future
    imports will match the surviving row by external_id.
    """
    GameObject = apps.get_model('compendium', 'GameObject')
    seen = set()
    duplicates = []
    queryset = (
        GameObject.objects.exclude(external_id=None)
        .exclude(external_id='')
        .order_by('pk')
        .only('id', 'system', 'object_type', 'external_id')
    )
    for obj in queryset.iterator():
        key = (obj.system, obj.object_type, obj.external_id)
        if key in seen:
            duplicates.append(obj.pk)
        else:
            seen.add(key)
    if duplicates:
        GameObject.objects.filter(pk__in=duplicates).update(external_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0003_alter_gameobject_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(blank_duplicate_external_ids, migrations.RunPython.noop),
        migrations.AddField(
            model_name='gameobject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_game_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='gameobject',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('system', 'object_type', 'external_id'), name='unique_external_id_per_system_type'),
        ),
    ]
