# Generated by Django 5.1 on 2026-02-08 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compendium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameObjectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(choices=[('monster', 'Monster'), ('spell', 'Spell'), ('item', 'Item'), ('character', 'Character'), ('npc', 'NPC'), ('misc', 'Misc')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='game_copy', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_instances', to='compendium.gameobject')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_instances', to='games.game')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['game', 'object_type', 'name'], name='games_gameo_game_id_a83c66_idx')],
            },
        ),
    ]
