# Generated by Django 5.2.8 on 2026-02-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gameplayer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gameplayer',
            new_name='games_gamep_game_id_b3319a_idx',
            old_name='games_gamep_game_id_73971b_idx',
        ),
    ]
