# Generated by Django 5.2.8 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_rename_games_gamep_game_id_73971b_idx_games_gamep_game_id_b3319a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="ac",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="base_stat_block",
            field=models.TextField(blank=True),
        ),
    ]
