# Generated by Django 5.2.8 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_gameplayer_ac_and_base_stat_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="strength",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="dexterity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="constitution",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="intelligence",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="wisdom",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="charisma",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
