# Generated by Django 5.2.8 on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_gameplayer_ability_scores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayer",
            name="base_stat_block",
        ),
    ]
