# Generated by Django 5.2.15 on 2026-06-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0004_gameobject_created_by_and_more'),
        ('games', '0008_remove_gameplayer_base_stat_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobjectinstance',
            name='base_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_instances', to='compendium.gameobject'),
        ),
        migrations.AlterField(
            model_name='gameobjectinstance',
            name='object_type',
            field=models.CharField(choices=[('monster', 'Monster'), ('spell', 'Spell'), ('item', 'Item'), ('class', 'Class'), ('race', 'Race'), ('feat', 'Feat'), ('background', 'Background'), ('condition', 'Condition'), ('character', 'Character'), ('npc', 'NPC'), ('misc', 'Misc')], db_index=True, max_length=32),
        ),
    ]
