# Generated by Django 5.1 on 2026-02-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('npc', 'NPC'), ('monster', 'Monster'), ('custom', 'Custom')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('hp_current', models.IntegerField(blank=True, null=True)),
                ('hp_max', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_entries', to='games.game')),
                ('object_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn_entries', to='games.gameobjectinstance')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['game', 'sort_order'], name='tracker_tur_game_id_f6dc84_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('game',), name='unique_current_turn_entry_per_game')],
            },
        ),
    ]
