# Generated by Django 5.2.8 on 2026-02-08 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnTrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('player', 'Player'), ('npc', 'NPC'), ('enemy', 'Enemy')], max_length=16)),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('hp_current', models.IntegerField(blank=True, null=True)),
                ('hp_max', models.IntegerField(blank=True, null=True)),
                ('items_text', models.TextField(blank=True)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('compendium_monster', 'Compendium Monster'), ('game_instance', 'Game Object Instance')], default='manual', max_length=32)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_rounds', models.PositiveIntegerField()),
                ('remaining_rounds', models.PositiveIntegerField()),
                ('is_running', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_effects', to='tracker.turntrackerentry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='TurnEntry',
        ),
        migrations.AddIndex(
            model_name='turntrackerentry',
            index=models.Index(fields=['user', 'sort_order'], name='tracker_tur_user_id_964fcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='turntrackerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user',), name='unique_current_tracker_entry_per_user'),
        ),
    ]
