# Generated by Django 5.2.8 on 2026-02-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_encounter"),
        ("tracker", "0002_turntrackerentry_statuseffect_delete_turnentry_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="turntrackerentry",
            name="unique_current_tracker_entry_per_user",
        ),
        migrations.AddField(
            model_name="turntrackerentry",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracker_entries",
                to="games.encounter",
            ),
        ),
        migrations.AddIndex(
            model_name="turntrackerentry",
            index=models.Index(fields=["user", "encounter", "sort_order"], name="tracker_tur_user_id_da6de8_idx"),
        ),
        migrations.AddConstraint(
            model_name="turntrackerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("encounter__isnull", True), ("is_current", True)),
                fields=("user",),
                name="unique_current_global_tracker_entry_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="turntrackerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("encounter__isnull", False), ("is_current", True)),
                fields=("user", "encounter"),
                name="unique_current_encounter_tracker_entry_per_user",
            ),
        ),
    ]
